// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wiyozzjvyhcbnufovacx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndpeW96emp2eWhjYm51Zm92YWN4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5MDE5NTcsImV4cCI6MjA3MDQ3Nzk1N30.8XyCv1cTJvQU5GsHNulJ4peopx1WtEXUCeX7d_Q2Vi0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});